### ISSUE TITLE
help

### ISSUE THREAD

**Issue by fokinhell** [drJeckyll/tumblr-chat-messages-downloader#3]
Hey I really want to use this but I have no knowledge on php or any of this coding stuff. Can I get help? What programs do I need

**Comment by rtanen** [comment]
You don't need to learn to code in PHP to use this project.

What you need to run this program is the terminal emulator on your computer, PHP, and a copy of this program. You probably already have the first two.

You might want to do a web search for something like "run command line application [my operating system]" – this is a pretty common thing for people to do, there should be lots of tutorials and stuff about it.

**Comment by rtanen** [comment]
Also, your concern isn't actually an issue with the project. If, once you familiarize yourself with concepts common to running any executable on the command line, you still find this particular project's documentation to be opaque, then that could be an issue with the project. While I can't close issues here, I would suggest that this issue be closed.

**Comment by fokinhell** [comment]
Thanks for the help. However I came across the same issue as the one posted before: 

Fetch: login, Array
(
)

Notice: Undefined offset: 1 in C:\Users\name\Desktop\tumblr.php on line 65
home, done.

Invlid username or password!

**Comment by wintersoldiers** [comment]
Hi, all. I'm running into the same problem, with the exception that I'm working with Mac OS X:

> Fetch: login, home, done.
> 
> Invlid username or password!

**Comment by TheVeeC** [comment]
This part worked fine for me (though I had a separate issue).  It took me a few tries to login, your username is actually your e-mail address you use normally to login (which threw me off).

Can you share the command you're using to sign in, with the actual e-mail/pass/blog title redacted?

Also, if you're still having trouble try using XAMPP, instead of just a straight PHP install.  XAMPP carries more libraries and extensions, including curl.

XAMPP can be installed in most Windows or Mac (OSX) environments.

**Comment by drJeckyll** [comment]
Please, report the issues on new repo: https://git.jeckyll.net/published/personal/tumblr-chat-messages-downloader
